# Generated by Django 4.2.4 on 2023-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_coach_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos'),
        ),
        migrations.AlterField(
            model_name='team',
            name='motto',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
