# Generated by Django 4.2.4 on 2023-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_logo_alter_team_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='CHN', max_length=4),
            preserve_default=False,
        ),
    ]
