# Generated by Django 4.2.4 on 2023-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_account'),
        ('teams', '0007_team_manager_owner_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='players.player'),
        ),
    ]
