# Generated by Django 4.2.4 on 2023-08-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('logo', models.ImageField(null=True, upload_to='competition_logos')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('logo', models.ImageField(null=True, upload_to='league_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_number_of_teams', models.IntegerField()),
                ('maximum_number_of_teams', models.IntegerField()),
                ('registration_fees', models.BigIntegerField()),
                ('competition_type', models.CharField(choices=[('Knock Out', 'Knock Out'), ('Ranking', 'Ranking')], max_length=16)),
                ('auto_shuffling', models.BooleanField(default=True)),
                ('match_duration', models.DurationField()),
                ('overtime_duration', models.DurationField()),
                ('extra_description', models.TextField(max_length=256, null=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.competition')),
            ],
            options={
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('home_team_points', models.IntegerField(default=0)),
                ('away_team_points', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='teams.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
    ]
