# Generated by Django 4.2.4 on 2023-08-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('leagues', '0002_rating_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personal_ratings', to='players.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='players.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
