# Generated by Django 4.2.4 on 2023-09-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_rating_match_rating_rated_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='competition_logos'),
        ),
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='extra_description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
