# Generated by Django 4.2.4 on 2023-09-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_match_date_alter_match_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='start_time',
            new_name='kick_off_time',
        ),
    ]
