# Generated by Django 4.2.4 on 2023-09-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_rename_start_time_match_kick_off_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='kick_off_time',
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
